name: integration_test_example
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 1.1.2
  mobx: 1.2.1+4
  flutter_mobx: 1.1.0+2
  flutter_secure_storage: 3.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.11.5
  mobx_codegen: 1.1.2
  integration_test: 1.0.2+3

flutter:
  uses-material-design: true
